"""empty message

Revision ID: 3896ce3cd25c
Revises: 772d738521da
Create Date: 2026-07-15 21:10:05.418644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3896ce3cd25c'
down_revision = '772d738521da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_encrypted', sa.Text(), nullable=True))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('password_encrypted')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('password_encrypted')

    # ### end Alembic commands ###
